/**
 * cesgen oracles — AI side.
 *
 * Loads examples/oracles.json (generated by scripts/cesgen-oracles.mjs) and
 * runs every oracle through PerceptualSpaceSimulator.processImmediate.  Each
 * oracle is a property of the form:
 *
 *   given input pattern P applied step-by-step to machine M, the engine
 *   must produce expected output O at M's output region after the final step.
 *
 * Single-step oracles cover isInitial vectors that emit output directly.
 * Chained oracles cover multi-step paths through nextVectorIds — the engine
 * must thread state correctly across processImmediate calls.
 *
 * The same oracles file is consumed by tests/cesgen_oracles_parity.cpp in
 * RealityEngine_CPP.  Identical pass-sets across the two runtimes is the
 * cross-runtime parity gate.
 *
 * Regenerate the oracle set after editing a machine JSON:
 *   node scripts/cesgen-oracles.mjs
 *
 * Drift gate (gates CI before this test runs):
 *   node scripts/cesgen-oracles.mjs --check
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { MachineLoader } from '../services/MachineLoader.js';
import { PerceptualSpaceSimulator } from '../engine/PerceptualSpaceSimulator.js';
import type { Machine } from '../models/Machine.js';

const __filename = fileURLToPath(import.meta.url);
const ROOT         = join(dirname(__filename), '../..');
const MACHINES_DIR = join(ROOT, 'examples', 'machines');
const ORACLES_FILE = join(ROOT, 'examples', 'oracles.json');

interface Region { offset: number; length: number }
interface Oracle {
  id: string;
  machineFile: string;
  machineId: string;
  sequenceId: string;
  vectorId: string;
  kind: 'single-step' | 'chained';
  depth: number;
  inputRegion: Region;
  inputs: number[][];
  expected: { region: Region; values: number[]; outputIndex: number; provenance?: string[] };
}

interface OracleFile {
  version: string;
  machineCount: number;
  oracleCount: number;
  histogram: Record<string, number>;
  oracles: Oracle[];
}

const oracleData: OracleFile = JSON.parse(readFileSync(ORACLES_FILE, 'utf8'));

// Cache one Machine instance per file — loading the JSON is the expensive part.
// processImmediate is stateful on the simulator, so we still build a fresh
// simulator + clone of the machine for each oracle so prior runs can't bleed
// state into the next.
const rawJsonByFile = new Map<string, string>();
function rawJson(file: string): string {
  let v = rawJsonByFile.get(file);
  if (v === undefined) {
    v = readFileSync(join(MACHINES_DIR, file), 'utf8');
    rawJsonByFile.set(file, v);
  }
  return v;
}

function freshMachine(file: string, oracleId: string): Machine {
  // Use a deterministic ID derived from the oracle to avoid collisions
  // between sequential test cases that touch the same machine file.
  return MachineLoader.loadFromJSON(rawJson(file), `oracle::${oracleId}`);
}

function arraysEqual(a: readonly number[], b: readonly number[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

function denseInput(region: Region, values: number[]): number[] {
  const v = new Array<number>(region.offset + region.length).fill(0);
  const n = Math.min(region.length, values.length);
  for (let i = 0; i < n; i++) v[region.offset + i] = values[i]!;
  return v;
}

function runOracle(o: Oracle): { mergeBatch: any[]; finalPs: number[] } {
  const m = freshMachine(o.machineFile, o.id);
  const sim = new PerceptualSpaceSimulator(0);
  sim.addMachine(m);

  let lastStep: any = null;
  for (const stepInput of o.inputs) {
    lastStep = sim.processImmediate(denseInput(o.inputRegion, stepInput));
  }
  return {
    mergeBatch: lastStep?.mergeBatch ?? [],
    finalPs:    lastStep?.perceptualSpace ?? [],
  };
}

// ── Suite ────────────────────────────────────────────────────────────────────

describe('cesgen oracles — AI runtime', () => {
  test('oracle file has the expected shape', () => {
    expect(oracleData.version).toBeDefined();
    expect(oracleData.oracleCount).toBeGreaterThan(0);
    expect(oracleData.oracles.length).toBe(oracleData.oracleCount);
    expect(oracleData.histogram['single-step']).toBeGreaterThan(0);
  });

  // Each oracle becomes its own test row.  Jest's test.each renders the
  // oracle ID into the failure name so triage is direct.
  describe.each(['single-step', 'chained'])('%s oracles', (kind) => {
    const oracles = oracleData.oracles.filter(o => o.kind === kind);

    test(`(${kind}) at least one oracle of this kind exists`, () => {
      expect(oracles.length).toBeGreaterThan(0);
    });

    test.each(oracles.map((o, idx): [string, Oracle] => [`[${idx}] ${o.id}`, o]))(
      '%s',
      (_label, o) => {
        const { mergeBatch } = runOracle(o);

        // The property under test: for this (machine, sequence) running this
        // input chain, the expected output value must appear in the final
        // step's mergeBatch at the expected region.  The engine may fire
        // additional outputs from sibling vectors that also match (GTE
        // semantics with super-threshold input causes multi-fire), so this
        // is a membership check — not a length-1 assertion.
        // Disambiguate by provenance tail: when multiple vectors in the
        // same sequence emit identical values (e.g. aict-saturated[1] and
        // aict-overloaded[1] both produce [0,0,0,0,1,0]), the right
        // mergeBatch entry is the one whose chain ENDS at this oracle's
        // emitter.  Fall back to value-match if no chain-aware hit exists
        // (single-step oracles where the emitter is the tail by construction).
        const provenanceMatch = mergeBatch.find((op: any) =>
          op.sequenceId === o.sequenceId &&
          op.region.offset === o.expected.region.offset &&
          op.region.length === o.expected.region.length &&
          arraysEqual(op.values, o.expected.values) &&
          Array.isArray(op.provenance) && op.provenance.length > 0 &&
          op.provenance[op.provenance.length - 1] === o.vectorId
        );
        const valueMatch = provenanceMatch ?? mergeBatch.find((op: any) =>
          op.sequenceId === o.sequenceId &&
          op.region.offset === o.expected.region.offset &&
          op.region.length === o.expected.region.length &&
          arraysEqual(op.values, o.expected.values)
        );
        if (!valueMatch) {
          throw new Error(
            `oracle ${o.id}: expected output ${JSON.stringify(o.expected.values)} ` +
            `not present in mergeBatch for sequence=${o.sequenceId}; ` +
            `actual=${JSON.stringify(mergeBatch.map((op: any) => op.values))}`
          );
        }

        // Provenance invariants.  For *single-step* oracles, the emitter
        // must appear in the chain (it's normally the only entry; with
        // multi-fire sibling matches it may not be the tail).  For
        // *chained* oracles the canonical assertions are:
        //   1. chain is non-empty
        //   2. chain terminates at the oracle's emitter
        //   3. chain length is within the maxChainDepth budget
        // We do NOT require the chain to equal the generator's expected
        // path exactly — Kleene-star and other branching state machines
        // legitimately have multiple paths to the same terminal, and the
        // engine picks one deterministically.  The properties we DO assert
        // are the load-bearing ones for the audit-loop story: the alert
        // payload carries a real chain that ends at the asserter.
        if (o.kind === 'chained' && provenanceMatch) {
          expect(provenanceMatch.provenance.length).toBeGreaterThan(0);
          expect(provenanceMatch.provenance[provenanceMatch.provenance.length - 1]).toBe(o.vectorId);
          expect(provenanceMatch.provenance.length).toBeLessThanOrEqual(8);
        } else if (o.kind === 'single-step') {
          expect(valueMatch.provenance).toContain(o.vectorId);
        }
      }
    );
  });
});
